name: tutor-prod
services:
  backend:
    build: backend
    command: ["flask", "run", "--host=0.0.0.0"]
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
      - FLASK_DEBUG=0
      - ALLOWED_ORIGINS=*
    env_file:
      - backend/.env 
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost/api/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    # restart: always

  frontend:
    build: 
      context: frontend
      dockerfile: Dockerfile.prod
    env_file:
      - frontend/.env.production

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend