# Staging: run local containers for tests
name: tutor-staging
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  backend:
    build: backend
    env_file:
      - backend/.env 
    environment:
      - FLASK_ENV=production
      - ALLOWED_ORIGINS=http://localhost:3000
      - REDIS_URL=redis://redis:6379
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost/api/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    # restart: always

  frontend:
    build: 
      context: frontend
      dockerfile: Dockerfile.prod
    env_file:
      - frontend/.env.production

  nginx:
    build: 
      context: nginx
      dockerfile: Dockerfile.staging
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend