# Staging: run local containers for tests
name: tutor-staging
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - speech-coach-backend
  backend:
    build: backend
    command: ["gunicorn", "-b", "0.0.0.0:5000", "app:app"]
    env_file:
      - backend/.env 
    environment:
      - FLASK_ENV=production
      - ALLOWED_ORIGINS=http://localhost:3000
      - REDIS_URL=redis://redis:6379
      - ACOUSTIC_URL=http://speech_assessment_prod-models-1:6000
    networks:
      - speech-coach-backend
      - speech-coach-frontend
    depends_on:
      - redis
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost/api/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    # restart: always

  frontend:
    build: 
      context: frontend
      dockerfile: Dockerfile.prod
    env_file:
      - frontend/.env.production
    networks:
      - speech-coach-frontend
  nginx:
    build: 
      context: nginx
      dockerfile: Dockerfile.staging
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - speech-coach-frontend
networks:
  speech-coach-backend:
    name: speech-coach-backend
  speech-coach-frontend:
    name: speech-coach-frontend