name: tutor-prod
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  backend:
    build: backend
    env_file:
      - backend/.env 
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost/api/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    # restart: always

  frontend:
    build: 
      context: frontend
      dockerfile: Dockerfile.prod
    env_file:
      - frontend/.env.production

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/ssl/certs:/etc/ssl/certs
      - /etc/ssl/private:/etc/ssl/private
    depends_on:
      - backend
      - frontend