name: tutor-prod
services:
  backend:
    build: backend
    command: ["flask", "run", "--host=0.0.0.0"]
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
      - FLASK_DEBUG=0
    ports:
      - "5000:5000"
    env_file:
      - backend/.env 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
  frontend:
    build: 
      context: frontend
      dockerfile: Dockerfile.prod
    env_file:
      - frontend/.env.production
    ports:
      - "3000:80"
