# Before using Nginx, we need local tests but may not neeed to be in docker. 
name: tutor-dev
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
  backend:
    build: backend
    command: ["flask", "run", "--host=0.0.0.0"]
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - ALLOWED_ORIGINS=http://localhost:3000
      - REDIS_URL=redis://localhost:6379
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/backend
    env_file:
      - backend/.env 
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
    #   interval: 1h
    #   timeout: 10s
    #   retries: 3
  frontend:
    build: 
      context: frontend
      dockerfile: Dockerfile.dev
    env_file:
      - frontend/.env.development
    ports:
      - "3000:3000"
    command: ["npm", "start"]
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend